# Generated by Django 6.0.3 on 2026-03-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='household_type',
            field=models.CharField(choices=[('CV', 'Civil Servant'), ('P', 'Public'), ('S', 'Staff'), ('M', 'Military')], default='P', max_length=2),
        ),
    ]
