# Generated by Django 6.0.3 on 2026-04-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_household_household_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='security_deposit',
            field=models.FloatField(default=1380.12),
        ),
        migrations.AddField(
            model_name='child',
            name='tuition_rate',
            field=models.FloatField(default=1380.12),
        ),
    ]
