# Generated by Django 6.0.3 on 2026-04-21 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_child_security_deposit_child_tuition_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name_plural': 'Children'},
        ),
        migrations.RemoveField(
            model_name='child',
            name='security_deposit',
        ),
        migrations.RemoveField(
            model_name='child',
            name='tuition_rate',
        ),
    ]
