# Generated by Django 6.0.3 on 2026-05-03 06:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_child_options_remove_child_security_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=Decimal('1380.12'), max_digits=8),
        ),
        migrations.AddField(
            model_name='child',
            name='tuition_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
