# Generated by Django 6.0.3 on 2026-05-09 20:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_child_security_deposit_child_tuition_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
