# Generated by Django 6.0.3 on 2026-05-09 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_household_uuid'),
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VolunteerHours',
            new_name='VolunteerEntry',
        ),
        migrations.AlterModelOptions(
            name='volunteeropportunity',
            options={'ordering': ['-event_date', '-created_at'], 'verbose_name': 'Volunteer Opportunity', 'verbose_name_plural': 'Volunteer Opportunities'},
        ),
    ]
