# Generated by Django 6.0.3 on 2026-05-10 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_rename_volunteerhours_volunteerentry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteerentry',
            options={'ordering': ['-service_date', '-created_at'], 'verbose_name_plural': 'Volunteer Entries'},
        ),
        migrations.RemoveField(
            model_name='volunteerentry',
            name='opportunity',
        ),
        migrations.RemoveField(
            model_name='volunteerentry',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='volunteerentry',
            name='reviewed_by',
        ),
    ]
