# Generated by Django 6.0.3 on 2026-05-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_alter_volunteerentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerentry',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
