# Generated by Django 6.0.3 on 2026-03-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capacity', models.PositiveIntegerField()),
                ('min_age_months', models.PositiveIntegerField(help_text='Minimum age in months')),
                ('max_age_months', models.PositiveIntegerField(help_text='Maximum age in months')),
                ('notes', models.TextField(blank=True)),
                ('primary_teachers', models.ManyToManyField(blank=True, related_name='primary_rooms', to='people.staff')),
            ],
        ),
    ]
