# Generated by Django 6.0.3 on 2026-05-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='department',
            field=models.CharField(choices=[('IN', 'Infant'), ('TL', 'Toddler'), ('TR', 'Preschool Transition'), ('PS', 'Preschool')], default='PS', max_length=2),
        ),
    ]
