# Generated by Django 5.1.6 on 2025-02-26 07:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Household",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "min_age",
                    models.PositiveIntegerField(help_text="Minimum age in months"),
                ),
                (
                    "max_age",
                    models.PositiveIntegerField(help_text="Maximum age in months"),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(help_text="Number of children allowed"),
                ),
                ("tuition_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("infant", "Infant (0-12 months)"),
                            ("young_toddler", "Young Toddler (12-18 months)"),
                            ("toddler", "Toddler (18-30 months)"),
                            (
                                "transitional_preschool",
                                "Transitional Preschool (30-42 months)",
                            ),
                            ("early_preschool", "Early Preschool (36-48 months)"),
                            ("preschool", "Preschool (48-60 months)"),
                        ],
                        help_text="Categorization based on age range",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "ordering": ["min_age"],
            },
        ),
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parents",
                        to="accc.household",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                (
                    "security_deposit",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("accc_enroll_date", models.DateField(blank=True, null=True)),
                ("date_enrolled_current_room", models.DateField(blank=True, null=True)),
                ("expected_move_up_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="accc.household",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="accc.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_moved_in", models.DateField()),
                ("date_moved_out", models.DateField(blank=True, null=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_history",
                        to="accc.child",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accc.room"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("infant_certification", models.BooleanField(default=False)),
                ("teacher_certification", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("teacher", "Teacher"),
                            ("floater", "Floater"),
                            ("chef", "Chef"),
                            ("director", "Director"),
                            ("admin", "Administrator"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "work_hours",
                    models.CharField(help_text="E.g., Mon-Fri 8am-4pm", max_length=50),
                ),
                (
                    "other_rooms",
                    models.ManyToManyField(
                        blank=True, related_name="additional_staff", to="accc.room"
                    ),
                ),
                (
                    "primary_room",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_staff",
                        to="accc.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VolunteerHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("value", models.PositiveIntegerField(help_text="Hours volunteered")),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hours",
                        to="accc.household",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Waitlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=1, help_text="Lower number = higher priority"
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="accc.child",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "date_added"],
            },
        ),
    ]
