# Generated by Django 5.1.6 on 2025-02-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="household",
            name="household_type",
            field=models.CharField(
                choices=[("CV", "Civil Servant"), ("P", "Public"), ("M", "Military")],
                default="P",
                help_text="Classify the household type.",
                max_length=2,
            ),
        ),
    ]
