# Generated by Django 5.1.6 on 2025-02-26 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accc", "0002_household_household_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="child",
            unique_together={("first_name", "last_name", "birth_date")},
        ),
    ]
