# Generated by Django 5.1.6 on 2025-02-27 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accc", "0003_alter_child_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="child",
            options={"verbose_name_plural": "Children"},
        ),
        migrations.AlterModelOptions(
            name="roomhistory",
            options={"verbose_name_plural": "Room Histories"},
        ),
        migrations.AlterModelOptions(
            name="staff",
            options={"verbose_name_plural": "Staff"},
        ),
        migrations.AlterUniqueTogether(
            name="roomhistory",
            unique_together={("child", "room")},
        ),
    ]
