# Generated by Django 5.1.6 on 2025-02-27 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accc", "0004_alter_child_options_alter_roomhistory_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="child",
            name="date_enrolled_current_room",
        ),
        migrations.AlterField(
            model_name="child",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="accc.room",
            ),
        ),
        migrations.CreateModel(
            name="NewEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accepted", models.BooleanField(default=False)),
                ("teacher_assessment", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("sent_welcome_email", models.BooleanField(default=False)),
                ("parents_agree", models.BooleanField(default=False)),
                ("add_to_procare", models.BooleanField(default=False)),
                ("add_to_db", models.BooleanField(default=False)),
                ("security_deposit", models.BooleanField(default=False)),
                ("child_files", models.BooleanField(default=False)),
                (
                    "parentemail1",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "parentemail2",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="accc.child",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newenrollments",
                        to="accc.room",
                    ),
                ),
            ],
            options={
                "unique_together": {("child", "room")},
            },
        ),
        migrations.CreateModel(
            name="RoomTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_assessment", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("sent_transition_email", models.BooleanField(default=False)),
                ("parents_agree", models.BooleanField(default=False)),
                ("updated_procare", models.BooleanField(default=False)),
                ("updated_db", models.BooleanField(default=False)),
                ("updated_tuition_rate", models.BooleanField(default=False)),
                ("complete", models.BooleanField(default=False)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_transitions",
                        to="accc.child",
                    ),
                ),
                (
                    "current_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="accc.room",
                    ),
                ),
                (
                    "new_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_transitions",
                        to="accc.room",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Room Histories",
                "unique_together": {("child", "current_room")},
            },
        ),
        migrations.CreateModel(
            name="Withdrawals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accepted", models.BooleanField(default=False)),
                ("teacher_assessment", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("sent_welcome_email", models.BooleanField(default=False)),
                ("parents_agree", models.BooleanField(default=False)),
                ("add_to_procare", models.BooleanField(default=False)),
                ("add_to_db", models.BooleanField(default=False)),
                ("security_deposit", models.BooleanField(default=False)),
                ("child_files", models.BooleanField(default=False)),
                (
                    "parentemail1",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "parentemail2",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals",
                        to="accc.child",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_withdrawals",
                        to="accc.room",
                    ),
                ),
            ],
            options={
                "unique_together": {("child", "room")},
            },
        ),
        migrations.DeleteModel(
            name="RoomHistory",
        ),
    ]
