# Generated by Django 5.1.6 on 2025-03-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accc", "0005_remove_child_date_enrolled_current_room_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roomtransition",
            options={
                "ordering": ("start_date",),
                "verbose_name_plural": "Room Transitions",
            },
        ),
        migrations.AddField(
            model_name="newenrollment",
            name="complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="withdrawals",
            name="complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="room",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("infant", "Infant (0-12 months)"),
                    ("young_toddler", "Young Toddler (12-18 months)"),
                    ("toddler", "Toddler (18-30 months)"),
                    ("transitional_preschool", "Transitional Preschool (30-48 months)"),
                    ("preschool", "Preschool (48-60 months)"),
                ],
                help_text="Categorization based on age range",
                max_length=30,
            ),
        ),
    ]
