# Generated by Django 5.1.6 on 2025-03-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accc", "0006_alter_roomtransition_options_newenrollment_complete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="accc_leave_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="child",
            name="enrolled",
            field=models.BooleanField(default=False),
        ),
    ]
