# Generated by Django 5.1.6 on 2025-03-14 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accc", "0007_child_accc_leave_date_child_enrolled"),
    ]

    operations = [
        migrations.RenameField(
            model_name="withdrawals",
            old_name="start_date",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="withdrawals",
            old_name="add_to_db",
            new_name="sent_email",
        ),
        migrations.RenameField(
            model_name="withdrawals",
            old_name="add_to_procare",
            new_name="updated_db",
        ),
        migrations.RenameField(
            model_name="withdrawals",
            old_name="child_files",
            new_name="updated_procare",
        ),
        migrations.RemoveField(
            model_name="withdrawals",
            name="parentemail1",
        ),
        migrations.RemoveField(
            model_name="withdrawals",
            name="parentemail2",
        ),
        migrations.RemoveField(
            model_name="withdrawals",
            name="security_deposit",
        ),
        migrations.RemoveField(
            model_name="withdrawals",
            name="sent_welcome_email",
        ),
        migrations.AlterField(
            model_name="withdrawals",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="withdrawals",
                to="accc.room",
            ),
        ),
    ]
