# Generated by Django 5.1.6 on 2025-03-14 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accc", "0008_rename_start_date_withdrawals_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "min_age",
                    models.PositiveIntegerField(help_text="Minimum age in months"),
                ),
                (
                    "max_age",
                    models.PositiveIntegerField(help_text="Maximum age in months"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="room",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rooms",
                to="accc.department",
            ),
        ),
    ]
