# Generated by Django 5.1.6 on 2025-03-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accc", "0009_department_room_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="max_age",
            field=models.PositiveIntegerField(
                blank=True, help_text="Maximum age in months", null=True
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="min_age",
            field=models.PositiveIntegerField(
                blank=True, help_text="Minimum age in months", null=True
            ),
        ),
    ]
