# Generated by Django 5.1.6 on 2025-03-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accc", "0010_alter_department_max_age_alter_department_min_age"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={"ordering": ["min_age"]},
        ),
        migrations.AlterModelOptions(
            name="withdrawals",
            options={"verbose_name_plural": "Withdrawals"},
        ),
        migrations.RenameField(
            model_name="withdrawals",
            old_name="accepted",
            new_name="refund_security_deposit",
        ),
        migrations.RenameField(
            model_name="withdrawals",
            old_name="sent_email",
            new_name="removed_child_files",
        ),
        migrations.RenameField(
            model_name="withdrawals",
            old_name="updated_db",
            new_name="removed_from_google",
        ),
        migrations.RenameField(
            model_name="withdrawals",
            old_name="updated_procare",
            new_name="removed_from_procare",
        ),
        migrations.AddField(
            model_name="withdrawals",
            name="sent_withdrawal_email",
            field=models.BooleanField(default=False),
        ),
    ]
