# Generated by Django 5.1.6 on 2025-03-17 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accc", "0011_alter_department_options_alter_withdrawals_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="withdrawals",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="withdrawals",
            name="room",
        ),
    ]
