# Generated by Django 6.0.3 on 2026-03-09 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveUpPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earliest_date', models.DateField(blank=True, help_text='Earliest possible move-up date', null=True)),
                ('planned_date', models.DateField(blank=True, help_text='Director planned move date', null=True)),
                ('readiness_level', models.IntegerField(blank=True, help_text='Teacher readiness score (1-5)', null=True)),
                ('teacher_notes', models.TextField(blank=True)),
                ('director_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moveup_plans', to='people.child')),
                ('current_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moveups_from', to='classrooms.room')),
                ('target_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moveups_to', to='classrooms.room')),
            ],
            options={
                'ordering': ['planned_date'],
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='people.child')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='classrooms.room')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Normal'), (3, 'Low')], default=2)),
                ('requested_start', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='people.child')),
                ('desired_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='classrooms.room')),
            ],
            options={
                'ordering': ['priority', 'created_at'],
            },
        ),
    ]
