# Generated by Django 6.0.3 on 2026-03-09 08:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
        ('people', '0002_alter_household_household_type'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitlistentry',
            options={},
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='desired_room',
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='priority',
        ),
        migrations.AddField(
            model_name='moveupplan',
            name='exit_type',
            field=models.CharField(choices=[('moveup', 'Move Up'), ('graduation', 'Graduation'), ('withdrawal', 'Withdrawal')], default='moveup', max_length=20),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='preferred_rooms',
            field=models.ManyToManyField(blank=True, to='classrooms.room'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('planned', 'Planned'), ('enrolled', 'Enrolled'), ('withdrawn', 'Withdrawn')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='moveupplan',
            name='target_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_moveups', to='classrooms.room'),
        ),
        migrations.AlterField(
            model_name='waitlistentry',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.child'),
        ),
        migrations.AlterField(
            model_name='waitlistentry',
            name='requested_start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AdmissionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('implemented', 'Implemented'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.child')),
                ('target_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.room')),
                ('waitlist_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_plans', to='planning.waitlistentry')),
            ],
        ),
    ]
