# Generated by Django 6.0.3 on 2026-05-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_alter_waitlistentry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveupplan',
            name='exit_type',
            field=models.CharField(choices=[('moveup', 'Move Up'), ('withdrawal', 'Withdrawal')], default='moveup', max_length=20),
        ),
    ]
